name: 'data_integration_project'
version: '1.0.0'

profile: 'data_integration_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  data_integration_project:
    bronze:
      +schema: raw
      +materialized: table

    silver:
      +schema: staging
      +materialized: view

    analytics:
      +schema: analytics
      +materialized: table

    reporting:
      +schema: reporting
      +materialized: view

seeds:
  data_integration_project:
    +schema: raw
    +quote_columns: false
