name: 'data_integration_project'
version: '1.3.1'

profile: 'data_integration_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  data_integration_project:
    bronze_layer:
      +schema: raw
      +materialized: table

    silver_layer:
      +schema: raw
      +materialized: table

    analytics:
      +schema: analytics
      +materialized: table

    reporting:
      +schema: reporting
      +materialized: view

seeds:
  data_integration_project:
    +schema: 
    +quote_columns: false
