{{ config(materialized='table') }}

WITH ranked AS (
  SELECT 
    CST_ID,
    CST_KEY,
    CST_FIRSTNAME,
    CST_LASTNAME,
    CST_MARITAL_STATUS,
    CST_GNDR,
    CST_CREATE_DATE,
    ROW_NUMBER() OVER (PARTITION BY CST_ID ORDER BY CST_CREATE_DATE DESC) AS row_num
  FROM {{ ref('cust_details') }}
)

SELECT 
  CST_ID,
  CST_KEY,
  CST_FIRSTNAME,
  CST_LASTNAME,
  CST_MARITAL_STATUS,
  CST_GNDR,
  CST_CREATE_DATE
FROM ranked
WHERE row_num = 1
  AND CST_ID IS NOT NULL